### ISSUE TITLE
Update Getting Started page

### ISSUE THREAD

**Issue by gangov** [AstroNvim/astronvim.github.io#20]
hey there, 

I was wondering if it makes sense to update the getting started page. 

Currently we have the following:

Terminal with true color support (for the default theme, otherwise it is dependent on the theme you are using)

and I totally missed that, spent a couple of hours trying to figure out why I was getting green screen when starting nvim with AstroVim until I found out that MacOS default terminal doesn't support TrueColor.

Some changes to the test like
Terminal with true color support (MacOS Terminal does not have true color support, hence the default theme might not work, otherwise it is dependent on the theme you are using)

Regards,

**Comment by mehalter** [comment]
Thank you for opening an issue, There is a popup on the Requirements specifically talking about MacOS and that they do not support true colors.

![2022-08-10_11:58:19_screenshot](https://user-images.githubusercontent.com/1591837/183956694-a1e0d1d5-237a-4c0b-b49f-f3580b152018.png)
