### ISSUE TITLE
Config options scroll off screen

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/astronvim.github.io#24]
[Available User Options](https://astronvim.github.io/Configuration/config_options) is not shown completely requiring the user to scroll back and forth.

![Screenshot_2022-08-26_11-42-32](https://user-images.githubusercontent.com/512222/186942753-11f652f1-db40-43db-a0e8-385fb8a5e4be.png)

**Comment by mehalter** [comment]
This is actually no longer the case after v3 and our more simplified list of user options :)
