### ISSUE TITLE
replicate-nvchad-statusline bug

### ISSUE THREAD

**Issue by jay-babu** [AstroNvim/astronvim.github.io#45]
Hello,

I am getting an error when attempting to replicate this.

https://astronvim.github.io/Recipes/status#replicate-nvchad-statusline

![image](https://user-images.githubusercontent.com/36803168/208260192-6532a523-76ea-4755-b21b-d90d80b3a3b5.png)

**Comment by jay-babu** [comment]
https://gist.github.com/jay-babu/1f5547566f5c387f805e128bb8525340

**Comment by mehalter** [comment]
You commented out the `blank_bg` color for some reason

**Comment by jay-babu** [comment]
This error is still coming up for me even on v3. I had commented that out to test out what was causing it to break

See latest commit with everything copied and pasted + some small stuff that can be ignored:
https://github.com/jay-babu/dotfiles/commit/59be70250f3bc5217dce6df60c186c977a625084

**Comment by jay-babu** [comment]
@mehalter

**Comment by mehalter** [comment]
@jay-babu are you using the new docs version? 


https://astronvim.github.io/nightly/Recipes/status#replicate-nvchad-statusline

**Comment by mehalter** [comment]
If you are, I can take a look tomorrow to see where you messed up copy/pasting the configuration. Could be a bug maybe, but I have done some pretty complete testing on this snippet

**Comment by jay-babu** [comment]
Yep!

https://github.com/jay-babu/dotfiles/blob/7e93f50d7d93d23398351b1761a50293ee2d140c/shell/.config/nvim/lua/user/plugins/core.lua#L49. Maybe it is the transparent mode? I will try turning it off tomorrow and see if that fixes it

**Comment by mehalter** [comment]
I found your issue. It looks like you haven't put the `heirline` options in the correct files. So it is never setting the colors or separators or anything. Make sure to check out the list here to see what tables should be which files/folders: https://astronvim.github.io/nightly/Configuration/config_options

**Comment by jay-babu** [comment]
Thanks! that worked, sorry for the trouble
