### ISSUE TITLE
Small issue in plugin documentation

### ISSUE THREAD

**Issue by LandonSchropp** [AstroNvim/astronvim.github.io#48]
When trying to disable a couple of built-in plugins, I ran into a small issue.

The [Basic Configuration documentation](https://astronvim.github.io/Configuration/basic_configuration) states:

``` lua
  plugins = {
    init = {
      -- You can disable default plugins as follows:
      -- ["goolord/alpha-nvim"] = { disable = true },
      ...
    }
  }
```

In order to disable the plugins, I had to move the disable code _outside_ of `init`.

**Comment by mehalter** [comment]
It is in the `init` table
