### ISSUE TITLE
I don't manage to overwrite the configuration of neo-tree

### ISSUE THREAD

**Issue by R3l4x3** [AstroNvim/astronvim.github.io#73]
I've now tried several variations I've seen here in some closed issues, but no matter how I try, I can't manage to override neo-tree's configuration. 

This is what my user/init.lua currently looks like, however the files are still hidden.

```lua
return {
  plugins = {
    ["neo-tree"] = {
      filesystem = {
        filtered_items = {
          visible = true,
          hide_gitignored = false,
          hide_dotfiles = false,
        },
      },
    },
  },
}
```

I'm fairly new to neovim and AstroNvim, so I'm running out of ideas.

**Comment by mehalter** [comment]
Specifically here are the documentation for customizing plugins: https://astronvim.com/Recipes/custom_plugins

**Comment by R3l4x3** [comment]
Hi @mehalter 
thank you for your response. I closed this issue because I saw that I ended up in the wrong repo here. Sorry for that. 

I'll have a look at the links you gave me and hope to get the issue solved ;) thanks
