### ISSUE TITLE
Adding links to the repositories of the used plugins

### ISSUE THREAD

**Issue by R3l4x3** [AstroNvim/astronvim.github.io#76]
Although there is a list of links to the respective Github repos in the acknowledgements section, I only came across it by accident.

I would find it helpful if the links to the respective repos were included directly in the "Default Plugin Configurations" section. E.g. the respective headline linked.

I would also offer to make this change to the documentation. Is this desired, or should the Acknowledgements section be the only one that contains the links?

**Comment by mehalter** [comment]
Adding links to the default plugin configuration section would be great! Any PRs would be greatly appreciated to help add that as well :) thanks for the recommendation @R3l4x3 !

**Comment by mehalter** [comment]
You will want to make sure when you are making changes to `docs/` that you check the `nightly` version and not the tagged release version. The versioned docs shouldn't be changed directly. I can backport doc chaanges if we need to. But it is not necessary. Just make sure in your browser that you are selecting "Nightly" from the version dropdown
