### ISSUE TITLE
Update version to 3.12 on the website

### ISSUE THREAD

**Issue by oneslash** [AstroNvim/astronvim.github.io#79]
Hi,

It still shows the old version https://astronvim.com/

**Comment by mehalter** [comment]
The way docusaurus works with versioning, each new version creates a full copy of the website and is very space inefficient. They recommend to minimize the number of times you need to use the versioning. Basically we are only updating the version as new changes are relevant like new features that show up in the documentation and then updating the documentation. We are just making sure that `astronvim.com` pulls up the latest and most relevant documentation. The version number you want to use is the one that is the most recent version number that isn't above the current version. It's a weird system and I'm not a huge fan of the docusaurus versioning set up but I'm not sure of a better way to do this :/
