### ISSUE TITLE
docs: Getting Started - incorrect link to AstroNvim user example 

### ISSUE THREAD

**Issue by practicalli-john** [AstroNvim/astronvim.github.io#89]
The [AstroNvim Getting Started page](https://astronvim.com/2.3.0) contains a `user_example` link to a non-existent path on GitHub

#### Reproduction
1.  Open <https://astronvim.com/2.3.0>
2.  Scroll to bottom of page to the Configuration section
3.  Click the link called `user_example`

A new page opens at <https://github.com/AstroNvim/AstroNvim/blob/main/lua/user_example> and shows a `404 - page not found` message

#### Resolution
The link should point to <https://github.com/AstroNvim/user_example>

**Comment by mehalter** [comment]
That repository does not support AstroNvim v2.0. This is an unsupported version as indicated by the documentation notice on that page. In previous versions the user example was shipped with AstroNvim. So simply look at the `user_example` folder on your machine for it if you have AstroNvim v2x. We do not support those older versions any more and do not provide updates. If you want a link to the old version it can be found here: https://github.com/AstroNvim/AstroNvim/blob/v2.3.0/lua/user_example/init.lua

**Comment by practicalli-john** [comment]
Apologies, I am unsure how I ended up on the older version of the documentation.  I should have spotted that when creating the issue.

Thanks for a very useful project, its helped me a lot.
